### ISSUE TITLE
How to use SearchResult? I need use your library.

### ISSUE THREAD

**Issue by eduardohenriquern** [shibme/omdb-java#1]
As an activity of a discipline, I have to implement a KNN algorithm for classifying films and need to use IMDB data on training of this algorithm. Its implementation is interesting I'd like to know how to use it in my project.

Thanks

**Comment by shibme** [comment]
Hello Ed,

I don't have any documentation written for this library for now. Assuming that you are using one of the fancy IDEs like Intellij IDEA or Eclipse, the work is pretty much simple. just add the library to your maven or gradle dependency as given in the readme file, and then create an instance for the OMDBService file. Use the available methods of that instance to perform search.

**Comment by shibme** [comment]
You can [get in touch with me over telegram](https://telegram.me/shibme) for more information.
